version: "3"

volumes:
  postgres:

services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins_net
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=asdfhadsf
  

networks:
  jenkins_net: {}
