version: "3"

volumes:
  postgres:
  nextcloud:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asdfhadsf
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=db
